name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: git submodule update --init --recursive

      - run: sudo apt-get update
      - run: sudo apt-get install -y lcov

      - run: cmake -H. -B_build -DBUILD_TESTS=ON
      - run: cmake --build _build
      - run: ctest --test-dir _build --output-on-failure

      - run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' 'third-party/*' --output-file coverage.info

      - uses: coverallsapp/github-action@v2
        with:
          file: coverage.info
